spring:
      datasource:
                jdbc-url: jdbc:mysql://localhost:3306/spring_batch
                username: root
                password: root
                
      universitydatasource:
                jdbc-url: jdbc:mysql://localhost:3306/university
                username: root
                password: root
      
      allow-circular-references: true
      
      
      main:
          allow-circular-references: true